# This is a basic workflow to help you get started with Actions

name: PyTest all supported builds

env:
  ZENDESK_KEY: ${{ secrets.ZENDESK_KEY}}
  ZENDESK_HOST: ${{ secrets.ZENDESK_HOST}}
  FRESHDESK_KEY: ${{ secrets.FRESHDESK_KEY}}
  FRESHDESK_HOST: ${{ secrets.FRESHDESK_HOST}}
  TEST_EMAIL: ${{ secrets.TEST_EMAIL}}
  JIRA_HOST_1: ${{secrets.JIRA_HOST_1}}
  JIRA_KEY_1: ${{secrets.JIRA_KEY_1}}
  SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
  SLACK_TOKEN_TEST: ${{secrets.SLACK_TOKEN_TEST}}
  TRELLO_KEY: ${{secrets.TRELLO_KEY}}
  TRELLO_TOKEN: ${{secrets.TRELLO_TOKEN}}
  GMAIL_REFRESH_TOKEN: ${{secrets.GMAIL_REFRESH_TOKEN_TEST}}
  GMAIL_SECRET_JSON: ${{secrets.GMAIL_SECRET_JSON}}
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pytest3-11:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.3
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      # Runs a set of commands using the runners shell
      - name: Test with pytest
        run: pytest -vv -m "not interactive"
  pytest3-10:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      # Runs a set of commands using the runners shell
      - name: Test with pytest
        run: pytest -vv -m "not interactive"

  pytest3-8:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      # Runs a set of commands using the runners shell
      - name: Test with pytest
        run: pytest -vv -m "not interactive"

  pytest3-9:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      # Runs a set of commands using the runners shell
      - name: Test with pytest
        run: pytest -vv -m "not interactive"

                  
            